### ISSUE TITLE
change in cy-panzoom location

### ISSUE THREAD

**Issue by metincansiper** [cytoscape/cytoscape.js-panzoom#10]
Hi,
I was using this extension with cytoscape.js 2.5.0 and some older versions. For this versions cy-panzoom was located on the top-left and inside of div containing the cy-network.

![panzoom_old](https://cloud.githubusercontent.com/assets/6534865/12458267/af34907e-bfb1-11e5-8d48-d9b957dae616.PNG)

Now, I am using cytoscape.js 2.5.4 and the cy-panzoom is located under the cy-network div as following,

![panzoom](https://cloud.githubusercontent.com/assets/6534865/12458306/ddb50604-bfb1-11e5-9f02-eb1947a6652d.PNG)

I think that with the latest version of cytoscape.js the location of cy-panzoom of this extension would be changed unintentionally.

And also I was wondering is there any option enabling us to set the position of the cy-panzoom?

**Comment by maxkfranz** [comment]
Thanks for letting me know; fixed in 2.1.4

**Comment by metincansiper** [comment]
@maxkfranz 
Thanks, I think that you prepended the panzoom instead of appending it and made the position of container absolute. Making the position absolute was problematic for me, but when I remove the following line "$container.css('position', 'absolute');" it worked fine.

**Comment by maxkfranz** [comment]
You're right.  It should be on the panzoom container, not the cy container.  Let me know if it works for you.  Thanks

**Comment by metincansiper** [comment]
Thanks, it seems to be working for me now.
