### ISSUE TITLE
cy.panzoom('destroy') error: $(this) -> $this

### ISSUE THREAD

**Issue by emelendez** [cytoscape/cytoscape.js-panzoom#12]
trying to destroy "panzoom" via: cy.panzoom('destroy') an ERROR is thrown in line 81, within function "destroy":
```
 $pz.data('cybdgs').forEach(function( l ){
          $(this).cytoscape('get').off( l.evt, l.fn );
        });
```
"**$(this)**" (empty object), should be "**$this**" (previously defined above)

**Comment by maxkfranz** [comment]
Thanks for the PR; closing...
