### ISSUE TITLE
Additional fit options

### ISSUE THREAD

**Issue by ugurdogrusoz** [cytoscape/cytoscape.js-panzoom#14]
We (@metincansiper) added additional parameters for fit in window functionality of this extension:

- whether or not fit should be animated (see how animated fit in window works here: http://cs.bilkent.edu.tr/~ivis/SBGNViz.js_editor/sample-app)

- a selector which decides on what nodes to perform the fit (we needed this for making sure hidden - currently not visible - graph objects are not considered during the operation)

@maxkfranz Let us know if you'd like either of these to be included in this extension.

**Comment by maxkfranz** [comment]
@ugurdogrusoz Great, I've added you to npm so you guys can push a 2.4.0 release with the new features: https://www.npmjs.com/package/cytoscape-panzoom

Thanks

**Comment by ugurdogrusoz** [comment]
@metincansiper Maybe we can add animated zoom as well, and use this extension out of box from that point on.

**Comment by ugurdogrusoz** [comment]
Let's drop animated zoom since it's problematic due to multiple calls to the associated function when zoom slider is used.

**Comment by metincansiper** [comment]
@ugurdogrusoz  @maxkfranz  
I drop animated zoom and published 2.4.0 with other changes mentioned in this issue.
