### ISSUE TITLE
Improve install documentation

### ISSUE THREAD

**Issue by cmdcolin** [cytoscape/cytoscape.js-panzoom#15]
Currently the documentation says to register panzoom as

```
panzoom( cytoscape )
```

It requires the jquery argument as well though

```
 panzoom( cytoscape, $ )
```

Also the relevant CSS needs to be included, i.e. cytoscape.js-panzoom.css and font-awesome, but this is not documented either, would be nice to have a note :)

**Comment by utkarshagarwal01** [comment]
Thanks @cmdcolin 

Please have the docs updated. I was stuck here for quite some time;

**Comment by maxkfranz** [comment]
You *can* specify a ref to jquery, but it shouldn't be necessary: 

https://github.com/cytoscape/cytoscape.js-panzoom/blob/8babbcc3fe970e179d2f40b4ce51b13dcd4a2399/cytoscape-panzoom.js#L573-L576

If you don't specify a jquery ref, it will just `require('jquery')` for you.  Make sure you install your peer dependencies properly and that your bundler (webpack, browserify, etc.) is configured properly.
