### ISSUE TITLE
can't work with react

### ISSUE THREAD

**Issue by july-12** [cytoscape/cytoscape.js-panzoom#18]
I got the error which is "$container.cytoscape is not a function" from console

**Comment by maxkfranz** [comment]
I don't think that's a React issue.

You need either pass jQuery when you `require()` the extension or you need to make sure `window.jQuery` is available.  See the readme for details

**Comment by july-12** [comment]
@maxkfranz I think I've already passed jQuery into initial of panzoom
here is what I did
```javascript
import cytoscape from 'cytoscape';
import cxtmenu from 'cytoscape-cxtmenu';
import jquery from 'jquery';
cxtmenu(cytoscape, jquery)
cy.cxtmenu({})
```

**Comment by maxkfranz** [comment]
Are you using ^1.4 || ^2.0?

**Comment by july-12** [comment]
well the version of jquery i am using is **"jquery": "^2.2.3"**

**Comment by maxkfranz** [comment]
It should generally work with any jq2.x

It's difficult to say what your issue is.  Have you tried debugging and stepping through the extension calls?  Do you have a small demo that reproduces this (built with Browserify, Webpack, or Rollup, I would assume)?

**Comment by july-12** [comment]
@maxkfranz It works for me now.  I installed this extension by npm, but now I just copy 'cytoscape-panzoom.js' file directly into my project, and then import it with relative path. eventually errors disappear from console.

**Comment by maxkfranz** [comment]
That shouldn't be necessary; you may want to check your Browserify or Webpack settings.  If it works for you as-is though, that's fine too.

**Comment by july-12** [comment]
I am not sure whether is the issue of Webpack, but the other extensions work in previous way. it's really strange,  panzoom can't get the cy from $contaner.cytoscape('get').  anyway thx for you help a lot :)
