### ISSUE TITLE
cytoscape js check if panzoom is registered

### ISSUE THREAD

**Issue by djangosdk** [cytoscape/cytoscape.js-panzoom#19]
I am using requirejs AMD and i have written a module .
at first works ok but when i try to reuse module , it throws error .See below.
````js
// reusable module definition
define(['jquery', 'cytoscape', 'cytoscape-panzoom'], function($, cytoscape, panzoom) {
  panzoom(cytoscape, $); // register extension
// use cytoscape with panzoom
  return {
    something: something
  };
});
```
**ERROR:**
```Can not register `panzoom` for `core` since `panzoom` already exists in the prototype and can not be overridden```

Is there a way to check safely that extension is registered ?

**Comment by djangosdk** [comment]
I found it. But it should be mentioned in docs at https://github.com/cytoscape/cytoscape.js-panzoom/blob/master/README.md

**Correct way to register cytoscape js extensions**
```js
      //register panzoom extension
      if (typeof cytoscape('core', 'panzoom') !== 'function') {
        panzoom(cytoscape, $);
      }
      // register edgehandles extension
      if (typeof cytoscape('core', 'edgehandles') !== 'function') {
        edgehandles(cytoscape, $);
      }
      // register navigator extension
      if (typeof cytoscape('core', 'navigator') !== 'function') {
        navigator(cytoscape, $);
      }
```

**Comment by maxkfranz** [comment]
None of that is documented APIs.  It's better to make sure your callback only executes once if you're interested in forwards compatibility.

**Comment by djangosdk** [comment]
@maxkfranz 
It will be helpful if each cytoscape extension always registers itself with jquery like panzoom does ```$.fn.cytoscapePanzoom```

This way much cleaner would be 
```js
if (!$().cytoscapePanzoom) {
   // register pan-zoom
 }
```

But unfortunately not all cytoscape plugins do that.

With reusable modules , we do need mechanism for safe registration of extensions.
Yes above method is not documented so I went thorugh source.
It will be very helpful to have a builtin function which could indicate if an extension is registered.
```cytoscape('core', 'panzoom')```  could be deprecated in future? 
Is there any more reliable solution ?

**Comment by maxkfranz** [comment]
I'm not making any guarantees about future compatibility of undocumented APIs.  The solution to your problem is to register the extension only once -- during the initialisation phase of your app.
