### ISSUE TITLE
Not work in cytoscape 3.2 packaged with parcel

### ISSUE THREAD

**Issue by Luomusha** [cytoscape/cytoscape.js-panzoom#24]
Hi,
   Im using this with parcel.But it show anything after I added it to my project.
package.json
>  "dependencies": {
    "cytoscape": "^3.2.12",
    "cytoscape-cose-bilkent": "^4.0.0",
    "cytoscape-panzoom": "^2.5.2"
  } 

>   cytoscape.use(coseBilkent)
    panzoom(cytoscape)
    const cy = cytoscape(config)

    var defaults = {
      zoomFactor: 0.05, // zoom factor per zoom tick
      zoomDelay: 45, // how many ms between zoom ticks
      minZoom: 0.1, // min zoom level
      maxZoom: 10, // max zoom level
      fitPadding: 50, // padding when fitting
      panSpeed: 10, // how many ms in between pan ticks
      panDistance: 10, // max pan distance per tick
      panDragAreaSize: 75, // the length of the pan drag box in which the vector for panning is calculated (bigger = finer control of pan speed and direction)
      panMinPercentSpeed: 0.25, // the slowest speed we can pan by (as a percent of panSpeed)
      panInactiveArea: 8, // radius of inactive area in pan drag box
      panIndicatorMinOpacity: 0.5, // min opacity of pan indicator (the draggable nib); scales from this to 1.0
      zoomOnly: false, // a minimal version of the ui only with zooming (useful on systems with bad mousewheel resolution)
      fitSelector: undefined, // selector of elements to fit
      animateOnFit: function () { // whether to animate on fit
        return false
      },
      fitAnimationDuration: 1000, // duration of animation on fit

      // icon class names
      sliderHandleIcon: 'fa fa-minus',
      zoomInIcon: 'fa fa-plus',
      zoomOutIcon: 'fa fa-minus',
      resetIcon: 'fa fa-expand'
    }

    cy.panzoom(defaults)

**Comment by maxkfranz** [comment]
https://github.com/cytoscape/cytoscape.js-panzoom#dependencies
