### ISSUE TITLE
Avoiding jQuery dependency?

### ISSUE THREAD

**Issue by KonradHoeffner** [cytoscape/cytoscape.js-panzoom#26]
Is it possible to use this without loading jQuery? Or is there an alternative Cytoscape.js zoom widget that doesnt depend on jQuery?

**Comment by maxkfranz** [comment]
This widget currently requires jQuery.  Given that Cytoscape supports ubiquitous gestures for zooming and panning, the use of a UI like this extension is a bit old-fashioned.  So, it's not currently a high priority to change the extension.

If you're interested in removing the jQuery dependency, we'd gladly accept a pull request.

**Comment by KonradHoeffner** [comment]
I looked at the code but unfortunately my experience with jQuery and Cytoscape plugin development is small so I wasn't successful in removing jQuery while preserving the functionality. So I will continue to use it with the jQuery dependency in place.
