### ISSUE TITLE
Faced one issue with angular import

### ISSUE THREAD

**Issue by Abhi5h3k** [cytoscape/cytoscape.js-panzoom#32]
I was implementing this extension for cytoscape.js in angular 2+.
I'm relatively new with angular 2+ and faced an issue while importing the **cytoscape-panzoom.js**

_Issue:_ 

Generally, we don't have hyphen  **'-'** in import name. so when I imported this library, Angular was unable to read the file name. It was reading **cytosacpe**-**panzoom** as two string literal 1[cytoscape] and 2[panzoom]. Due to this, it was also showing me an error for a duplicate identifier.

![image](https://user-images.githubusercontent.com/37928721/78478231-8d56d580-7762-11ea-8523-956f685562c2.png)

_Fix that worked for me:_
1. renamed the cytoscape-panzoom.js to cytoscapePanzoom.js (removing the hyphen)
2. then importing it.

![image](https://user-images.githubusercontent.com/37928721/78479830-fc342e80-7762-11ea-811e-ff5226ff2eb2.png)

 It worked fine after doing this. If someone faces this issue and has a right solution update me.

**Comment by DiligentTuolaji** [comment]
1. How you rename it? By changing file name in node_modules? By the way, this package  seems not work correctly
