### ISSUE TITLE
Using this within Angular

### ISSUE THREAD

**Issue by mbabatunde** [cytoscape/cytoscape.js-panzoom#34]
Has anyone been able to integrate this within their angular7 web app?

I was able to import and link everything, but the panzoom button is not appearing for me.

I've done something like the following in one component:
```javascript
import cytoscapePanzoom from "cytoscape-panzoom";
import * as $ from "jquery/dist/jquery.min.js";

...

cytoscapePanzoom(cytoscape, $);
cy.panzoom(defaults); // defaults from the README
```

I added the css files (font-awesome and cytoscape-panzoom ones) within the `index.html`

Is there something else I'm missing?

**Comment by JeevanPrasad** [comment]
were you able to get this working?

**Comment by mbabatunde** [comment]
No solution at the moment

**Comment by DarioDemix** [comment]
Hi, I've successfully integrated cytoscape-panzoom in an Angular (*v.11/12*) application.

The steps to make it works are: 
 - declare the variable *__require__*, which is a function, to import the plugin via CommonJS
 ``` typescript
 declare var require: any
 ``` 
 this function is provided by *__webpack__* which is built-in in Angular;
 - require *__cytoscape-panzoom__* in your component
``` typescript
const cytoscapePanzoom = require('cytoscape-panzoom');
```
- at this point the plugin works, but it doesn't see its CSS. This can be solved by exposing the .css files in *__angular.json__*
``` json
  "styles": [
              "src/styles.css",
              "./node_modules/cytoscape-panzoom/font-awesome-4.0.3/css/font-awesome.min.css",
              "./node_modules/cytoscape-panzoom/cytoscape.js-panzoom.css"
            ],
```
- the remaining configuration (like registering the plugin) is the same.

### For any doubt I created a simple repository in my GitHub: 
### [cytoscape-panzoom-in-angular](https://github.com/DarioDemix/cytoscape-panzoom-in-angular)

---

# Result

![panzoom](https://user-images.githubusercontent.com/47568450/123768914-0ba01a00-d8c9-11eb-89c5-77da8b2f19b4.jpg)

**Comment by DiligentTuolaji** [comment]
> Hi, I've successfully integrated cytoscape-panzoom in an Angular (_v.11/12_) application.
> 
> The steps to make it works are:
> 
> * declare the variable _**require**_, which is a function, to import the plugin via CommonJS
> 
> ```ts
> declare var require: any
> ```
> 
> this function is provided by _**webpack**_ which is built-in in Angular;
> 
> * require _**cytoscape-panzoom**_ in your component
> 
> ```ts
> const cytoscapePanzoom = require('cytoscape-panzoom');
> ```
> 
> * at this point the plugin works, but it doesn't see its CSS. This can be solved by exposing the .css files in _**angular.json**_
> 
> ```json
>   "styles": [
>               "src/styles.css",
>               "./node_modules/cytoscape-panzoom/font-awesome-4.0.3/css/font-awesome.min.css",
>               "./node_modules/cytoscape-panzoom/cytoscape.js-panzoom.css"
>             ],
> ```
> 
> * the remaining configuration (like registering the plugin) is the same.
> 
> ### For any doubt I created a simple repository in my GitHub:
> ### [cytoscape-panzoom-in-angular](https://github.com/DarioDemix/cytoscape-panzoom-in-angular)
> # Result
> ![panzoom](https://user-images.githubusercontent.com/47568450/123768914-0ba01a00-d8c9-11eb-89c5-77da8b2f19b4.jpg)

**Comment by DiligentTuolaji** [comment]
Why use require in frontend code? I can confirm this package does not work by the way "Import"
