### ISSUE TITLE
Unable to get component fully working

### ISSUE THREAD

**Issue by codeyourweb** [cytoscape/cytoscape.js-panzoom#35]
Hi, 

I'm trying to implement cytoscape-panzoom in a React.js application using cytoscape. zoom is working but it seems the control isn't fully working and i don't know how to solve this problem, maybe you'll see why it isn't running like i would like:
[Implementation result](https://imgur.com/a/KRVURam) versus [expected result](https://raw.githubusercontent.com/cytoscape/cytoscape.js-panzoom/master/img/preview.png)

configuration:
```
let panzoomDefaults = {
	zoomFactor: 0.05,
	zoomDelay: 45,
	minZoom: 0.1,
	maxZoom: 10,
	fitPadding: 50,
	panSpeed: 10,
	panDistance: 10,
	panDragAreaSize: 75,
	panMinPercentSpeed: 0.25,
	panInactiveArea: 8,
	panIndicatorMinOpacity: 0.5,
	zoomOnly: false,
	fitSelector: undefined,
	animateOnFit: function(){
	  return false;
	},
	fitAnimationDuration: 1000,
	sliderHandleIcon: 'fa fa-minus',
	zoomInIcon: 'fa fa-plus',
	zoomOutIcon: 'fa fa-minus',
	resetIcon: 'fa fa-expand'
  };
```

-- jquery@3.5.1
-- react@16.13.1
-- cytoscape@3.15.2
-- cytoscape-panzoom@2.5.3

**Comment by liangxuchao** [comment]
Hi, 

For people who might still looking for solution, remember to import the css for panzoom

import "cytoscape-panzoom/cytoscape.js-panzoom.css";
