### ISSUE TITLE
Layout name as option to cy.panzoom()

### ISSUE THREAD

**Issue by devradhika** [cytoscape/cytoscape.js-panzoom#4]
Ho to send the name of the layout to the 
cy.panzoom({
//options go here
});

Tried directly name of the layouit,howevere it is giving error.

**Comment by maxkfranz** [comment]
You don't pass layouts to the panzoom extension...

**Comment by DiligentTuolaji** [comment]
> Ho to send the name of the layout to the cy.panzoom({ //options go here });
> 
> Tried directly name of the layouit,howevere it is giving error.

Why there is no property "panzoom" in my cy? version 3.21.1
